// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAusxX9eqbq6IMOWertQovzNZcmRL2qySA',
    appId: '1:1053839377727:web:b1a862233281f58af03f8a',
    messagingSenderId: '1053839377727',
    projectId: 'shopping-53b35',
    authDomain: 'shopping-53b35.firebaseapp.com',
    storageBucket: 'shopping-53b35.appspot.com',
    measurementId: 'G-CV8EEM2JCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoU8cJsOj0pK2EV4AYLjACLteGV3AX_z4',
    appId: '1:1053839377727:android:3b4a378a583f4442f03f8a',
    messagingSenderId: '1053839377727',
    projectId: 'shopping-53b35',
    storageBucket: 'shopping-53b35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsDeI211gj2bI9Tlq6tjDD1X3M0pb061I',
    appId: '1:1053839377727:ios:7360656250f77ae4f03f8a',
    messagingSenderId: '1053839377727',
    projectId: 'shopping-53b35',
    storageBucket: 'shopping-53b35.appspot.com',
    iosClientId: '1053839377727-476e1f9agi1trkdgcoccpg9ij3ise96b.apps.googleusercontent.com',
    iosBundleId: 'com.fisis.shopping.list.shoppingList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsDeI211gj2bI9Tlq6tjDD1X3M0pb061I',
    appId: '1:1053839377727:ios:7360656250f77ae4f03f8a',
    messagingSenderId: '1053839377727',
    projectId: 'shopping-53b35',
    storageBucket: 'shopping-53b35.appspot.com',
    iosClientId: '1053839377727-476e1f9agi1trkdgcoccpg9ij3ise96b.apps.googleusercontent.com',
    iosBundleId: 'com.fisis.shopping.list.shoppingList',
  );
}
